package main;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.URL;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author josej
 */
public class ConversorPanel extends javax.swing.JFrame {
    
    /**
     * Creates new form ConversorPanel
     */
    public ConversorPanel() {
        initComponents(); 
        getContentPane().setBackground(new java.awt.Color(177, 249, 150));
        String u = "https://free.currconv.com/api/v7/convert?q=";
        String baseCurrency = "USD";
        String termCurrency = "EUR";
        String charset = "UTF-8";
        try {
            URL url = new URL(u + baseCurrency + "_" + termCurrency + "&compact=ultra&apiKey=6b09f9de604b6502aa1f");
            BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream(), charset));
            String line = reader.readLine();
            rateDollarToEuro = Double.parseDouble(line.substring(line.indexOf(":")+1,line.length()-1));
        } catch (Exception ex) {
            System.out.println("Error al acceder al valor de cambio, se usará un valor por defecto");
            rateDollarToEuro = 0.85;
        }
        
        System.out.println("Valor de cambio de dolares a euros: " + rateDollarToEuro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTextField = new javax.swing.JTextField();
        outputTextField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        buttonToEur = new javax.swing.JButton();
        buttonToClear = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        buttonToUSD = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        inputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTextFieldKeyPressed(evt);
            }
        });

        outputTextField.setEditable(false);

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        titleLabel.setText("Conversor € / $");

        buttonToEur.setText("Convertir a Euro");
        buttonToEur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToEurActionPerformed(evt);
            }
        });

        buttonToClear.setText("Limpiar");
        buttonToClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToClearActionPerformed(evt);
            }
        });

        errorLabel.setBackground(new java.awt.Color(255, 255, 255));
        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLabel.setText(" ");

        buttonToUSD.setText("Convertir a Dolar");
        buttonToUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToUSDActionPerformed(evt);
            }
        });

        amountLabel.setText("Introduce una cantidad:");

        jLabel1.setForeground(new java.awt.Color(0, 193, 100));
        jLabel1.setText("Autores: Anayara y José Juan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonToEur)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(amountLabel)
                                .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonToUSD))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonToClear, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(amountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(errorLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonToEur)
                    .addComponent(buttonToUSD))
                .addGap(32, 32, 32)
                .addComponent(buttonToClear)
                .addGap(4, 4, 4)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonToEurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToEurActionPerformed
        if (inputTextField.getText().length()!=0) {
            outputTextField.setText("Son " + String.format("%.2f", 
                    Double.parseDouble(inputTextField.getText().replace(',', '.'))*rateDollarToEuro) + " euros");
            errorLabel.setText(" ");
        }
    }//GEN-LAST:event_buttonToEurActionPerformed

    private void buttonToClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToClearActionPerformed
        inputTextField.setText("");
        outputTextField.setText("");
        errorLabel.setText(" ");
    }//GEN-LAST:event_buttonToClearActionPerformed

    private void inputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTextFieldKeyPressed
        // Comprobamos si el número seguiría siendo válido tras añadir el nuevo input
        if ((inputTextField.getText()+evt.getKeyChar()).matches("([0-9]*)([.,])?([0-9]{0,2})") 
                || evt.getKeyCode() == java.awt.event.KeyEvent.VK_BACK_SPACE){
           inputTextField.setEditable(true);
           errorLabel.setText(" ");
        } else {
            inputTextField.setEditable(false);
            if (evt.getKeyChar()== '.' || evt.getKeyChar() == ',')
                errorLabel.setText("Solo se acepta un punto o coma");
            else
                if ((inputTextField.getText().contains(".") || inputTextField.getText().contains(","))
                        && Character.isDigit(evt.getKeyChar()))
                   errorLabel.setText("Solo se aceptan dos decimales");
                else
                    errorLabel.setText("Solo se aceptan números");
                   
        }
    }//GEN-LAST:event_inputTextFieldKeyPressed

    private void buttonToUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToUSDActionPerformed
        if (inputTextField.getText().length()!=0) {
            outputTextField.setText("Son " + String.format("%.2f", 
                    Double.parseDouble(inputTextField.getText().replace(',', '.'))/rateDollarToEuro) + " dolares");
            errorLabel.setText(" ");
        }
    }//GEN-LAST:event_buttonToUSDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton buttonToClear;
    private javax.swing.JButton buttonToEur;
    private javax.swing.JButton buttonToUSD;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField outputTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private Double rateDollarToEuro;
}
